### ISSUE TITLE
Required file: stylesheets cannot be found

### ISSUE THREAD

**Issue by benji822** [nature-of-code/noc-book-2-archive#94]
Anyone received this kind of error?
After build the file is there, but all the styles didn't included

Error: Cannot find module '/Users/../../../noc-book-2/node_modules/stylesheets'
Require stack:
 /Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/plugin_executer.js
 /Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/build.js
 /Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Executer.requirePlugin (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/plugin_executer.js:150:28)
    at Executer.<anonymous> (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/plugin_executer.js:121:39)
    at wrapper (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/node_modules/lodash/lodash.js:4929:19)
    at arrayEach (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/node_modules/lodash/lodash.js:9342:14)
    at Executer.requirePlugins (/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/plugin_executer.js:117:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/plugin_executer.js',
    '/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/build.js',
    '/Users/../.nvm/versions/node/v12.4.0/lib/node_modules/magicbook/src/index.js'
  ]
}
Required file: stylesheets cannot be found
Cannot register permalinks . stylesheets:insert not found
Cannot register katex:setup . stylesheets:move not found

**Comment by shiffman** [comment]
I've updated magicbook and this is resolved now! https://github.com/magicbookproject/magicbook/pull/49
